services:
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            - TZ=UTC
        env_file:
            - .env.db
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - beetrack-net

    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - TZ=UTC
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - "8000:8000"
        networks:
            - beetrack-net

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "3000:80"
        depends_on:
            - api
        networks:
            - beetrack-net

volumes:
    pgdata:

networks:
    beetrack-net:
