services:
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            - TZ=UTC
        env_file:
            - .env.db
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - beetrack-net

    redis:
        image: redis:8.2-alpine
        restart: unless-stopped
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - "6379:6379"
        networks:
            - beetrack-net

    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - TZ=UTC
            - RATE_LIMIT_STORAGE=redis
            - REDIS_URL=redis://redis:6379/0
        env_file:
            - .env
        depends_on:
            - db
            - redis
        ports:
            - "8000:8000"
        networks:
            - beetrack-net

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "3000:80"
        depends_on:
            - api
        networks:
            - beetrack-net

volumes:
    pgdata:

networks:
    beetrack-net:
