from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from app.database import get_db
from app.services.auth import requires_role, get_current_user
from app.services import export
from app.utils.logger import log_event
from app import models, schemas

router = APIRouter()


@router.get("/orders/csv", response_class=FileResponse)
def download_orders_csv(
    db: Session = Depends(get_db),
    current_user: str = Depends(requires_role("admin"))
):
    path = export.export_orders_to_csv(db)
    if not path:
        log_event(f"Export failed: No orders to export for admin {current_user.username}")
        raise HTTPException(status_code=404, detail="No orders to export")
    log_event(f"Orders CSV exported by admin {current_user.username}")
    return FileResponse(path, media_type="text/csv", filename="orders.csv")


@router.get("/orders/pdf", response_class=FileResponse)
def download_orders_pdf(
    db: Session = Depends(get_db),
    current_user: str = Depends(requires_role("admin"))
):
    path = export.export_orders_to_pdf(db)
    if not path:
        log_event(f"Export failed: No orders to export for admin {current_user.username}")
        raise HTTPException(status_code=404, detail="No orders to export")
    log_event(f"Orders PDF exported by admin {current_user.username}")
    return FileResponse(path, media_type="application/pdf", filename="orders.pdf")


@router.get("/inspections/pdf", response_class=FileResponse)
def download_inspections_pdf(
    db: Session = Depends(get_db),
    current_user: str = Depends(requires_role("admin"))
):
    path = export.export_inspections_to_pdf(db)
    if not path:
        log_event(f"Export failed: No inspections to export for admin {current_user.username}")
        raise HTTPException(status_code=404, detail="No inspections to export")
    log_event(f"Inspections PDF exported by admin {current_user.username}")
    return FileResponse(path, media_type="application/pdf", filename="inspections.pdf")


@router.post("/filtered/orders", response_class=FileResponse)
def export_filtered_orders(
    filters: schemas.OrderExportFilter,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    path = export.export_orders_filtered(db, current_user, filters)
    if not path:
        raise HTTPException(status_code=404, detail="No orders matched filters or access denied")
    filename = path.split("/")[-1]
    media_type = "text/csv" if filters.format == schemas.ExportFormat.csv else "application/pdf"
    log_event(f"Orders filtered export generated by {current_user.username}")
    return FileResponse(path, media_type=media_type, filename=filename)


@router.post("/filtered/inspections", response_class=FileResponse)
def export_filtered_inspections(
    filters: schemas.InspectionExportFilter,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    path = export.export_inspections_filtered(db, current_user, filters)
    if not path:
        raise HTTPException(status_code=404, detail="No inspections matched filters or access denied")
    filename = path.split("/")[-1]
    media_type = "text/csv" if filters.format == schemas.ExportFormat.csv else "application/pdf"
    log_event(f"Inspections filtered export generated by {current_user.username}")
    return FileResponse(path, media_type=media_type, filename=filename)


@router.post("/filtered/hives", response_class=FileResponse)
def export_filtered_hives(
    filters: schemas.HiveExportFilter,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    path = export.export_hives_filtered(db, current_user, filters)
    if not path:
        raise HTTPException(status_code=404, detail="No hives matched filters or access denied")
    filename = path.split("/")[-1]
    media_type = "text/csv" if filters.format == schemas.ExportFormat.csv else "application/pdf"
    log_event(f"Hives filtered export generated by {current_user.username}")
    return FileResponse(path, media_type=media_type, filename=filename)


@router.post("/filtered/apiaries", response_class=FileResponse)
def export_filtered_apiaries(
    filters: schemas.ApiaryExportFilter,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    path = export.export_apiaries_filtered(db, current_user, filters)
    if not path:
        raise HTTPException(status_code=404, detail="No apiaries matched filters or access denied")
    filename = path.split("/")[-1]
    media_type = "text/csv" if filters.format == schemas.ExportFormat.csv else "application/pdf"
    log_event(f"Apiaries filtered export generated by {current_user.username}")
    return FileResponse(path, media_type=media_type, filename=filename)
