"""fix identity on apiary tables id columns

Revision ID: 20250830_01_fix_apiary_identity
Revises: 20250829_02_link_h_apiary
Create Date: 2025-08-30
"""
from alembic import op

revision = '20250830_01_fix_apiary_identity'
down_revision = '20250829_02_link_h_apiary'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiary_members' AND column_name = 'id' AND is_identity = 'YES'
            ) THEN
                -- already identity, nothing to do
                NULL;
            ELSIF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiary_members' AND column_name = 'id' AND column_default IS NOT NULL
            ) THEN
                -- has a default already (e.g., sequence), leave as is
                NULL;
            ELSE
                EXECUTE 'ALTER TABLE apiary_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;
        END$$;
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiary_invitations' AND column_name = 'id' AND is_identity = 'YES'
            ) THEN
                NULL;
            ELSIF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiary_invitations' AND column_name = 'id' AND column_default IS NOT NULL
            ) THEN
                NULL;
            ELSE
                EXECUTE 'ALTER TABLE apiary_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;
        END$$;
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE apiary_members ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE apiary_invitations ALTER COLUMN id DROP IDENTITY IF EXISTS;")
