"""ensure identity/sequence on apiaries.id and restart to max+1

Revision ID: 20250831_01_fix_identity_restart
Revises: 20250830_02_fix_identity_restart
Create Date: 2025-08-31
"""
from alembic import op

revision = '20250831_01_fix_identity_restart'
down_revision = '20250830_02_fix_identity_restart'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiaries' AND column_name = 'id' AND is_identity = 'YES'
            ) THEN
                -- already identity, nothing to do
                NULL;
            ELSIF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiaries' AND column_name = 'id' AND column_default IS NOT NULL
            ) THEN
                -- has a default already (likely nextval from SERIAL), leave as is
                NULL;
            ELSE
                -- no identity and no default => add identity
                EXECUTE 'ALTER TABLE apiaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;
        END$$;
        """
    )

    op.execute(
        """
        DO $$
        DECLARE v bigint;
        DECLARE seq_name text;
        DECLARE col_default text;
        BEGIN
            SELECT COALESCE(MAX(id), 0) + 1 INTO v FROM apiaries;

            -- Check if column is identity
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'apiaries' AND column_name = 'id' AND is_identity = 'YES'
            ) THEN
                EXECUTE format('ALTER TABLE apiaries ALTER COLUMN id RESTART WITH %s', v);
            ELSE
                -- Fallback for SERIAL/sequence-backed column
                SELECT pg_get_serial_sequence('apiaries', 'id') INTO seq_name;
                IF seq_name IS NOT NULL THEN
                    EXECUTE format('SELECT setval(%L, %s, false)', seq_name, v);
                END IF;
            END IF;
        END$$;
        """
    )


def downgrade() -> None:
    pass
